"""Player email and password

Revision ID: 61a2ad65d74b
Revises: 1db3f7dc7f1f
Create Date: 2024-11-30 17:33:13.314680

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '61a2ad65d74b'
down_revision: Union[str, None] = '1db3f7dc7f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('email', sa.String(length=20), nullable=False))
    op.add_column('player', sa.Column('password', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'password')
    op.drop_column('player', 'email')
    # ### end Alembic commands ###
