"""
Initial migration

Revision ID: 7b8e6bd8abe4
Revises:
Create Date: 2024-10-24 08:43:30.161849

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b8e6bd8abe4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_player_id"), "player", ["id"], unique=False)
    op.create_index(
        op.f("ix_player_username"), "player", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_username"), table_name="player")
    op.drop_index(op.f("ix_player_id"), table_name="player")
    op.drop_table("player")
    # ### end Alembic commands ###
